let apartments = [
    {
      id: 1,
      street: "Andros Pl",
      unit: "1",
      city: "San Diego",
      state: "CA",
      square_footage: 1200,
      price: "2,500",
      bedrooms: 2,
      bathrooms: 2,
      pets: "yes",
      image: "../assets/1", 
      user_id: 1,
    },
    {
      id: 2,
      street: "Andros Pl",
      unit: "1",
      city: "San Diego",
      state: "CA",
      square_footage: 1200,
      price: "2,500",
      bedrooms: 2,
      bathrooms: 2,
      pets: "yes",
      image: "../assets/2", 
      user_id: 2,
    },
    {
      id: 3,
      street: "Andros Pl",
      unit: "1",
      city: "San Diego",
      state: "CA",
      square_footage: 1200,
      price: "2,500",
      bedrooms: 2,
      bathrooms: 2,
      pets: "yes",
      image: "../assets/3", 
      user_id: 3,
    },
  ];
  
  export default apartments;
  